import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./global.css"; //CSS página

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TH TECNOLOGIA", //Título página
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="description" content="TH Tecnologia, Certificado Digital, Emissão Online, Planos e Seguros"/>
        <meta name="keywords" content="certificado digital, nuvem, renovação, emissão online, plano de saúde, seguro de carro, certificado a1, certificado a3, mídia"/>
        <meta name="author" content="TH Tecnologia"/>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}